### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [kamilp999/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Add file extension
- [ ] We should have more than one class
- [ ] Class is not **cohesive**. We can create completely different objects with it 👎 

**Task 2**
- [x] We should have more constructors.
- [x] `Exer2` is bad name for class.
- [x] `Name` should have better name. Something like `greetings`
